name: ci

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build
    strategy:
      matrix:
        node-version: [16, 17]
    runs-on: ubuntu-latest

    steps:
      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
        id: node

      - name: Check out the code
        uses: actions/checkout@v2.3.4

      - name: Get dependencies
        run: |
          npm ci

      - name: Lint
        run: |
          npm run lint

      - name: Build
        run: |
          npm run build

      - name: Test
        run: |
          npm run test

      - uses: actions/upload-artifact@v2
        with:
          name: coverage-report-${{ matrix.node-version }}
          path: coverage/lcov-report
